# Generated by Django 3.2 on 2022-06-01 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=255)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=255)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('main_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.mainkeywordmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='no token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(default='member', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_token', models.CharField(default='no token', max_length=100)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageListMetaDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_keyword', models.TextField(blank=True, null=True)),
                ('shorten_keyword', models.TextField(blank=True, null=True)),
                ('page_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.pagelistmodel')),
            ],
        ),
        migrations.AddField(
            model_name='mainkeywordmodel',
            name='page_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.pagelistmodel'),
        ),
        migrations.CreateModel(
            name='LongTailSubKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtail_name', models.TextField(blank=True, null=True)),
                ('shorten_name', models.TextField(blank=True, null=True)),
                ('link_href', models.TextField(blank=True, null=True)),
                ('link_href_shorten_name', models.TextField(blank=True, null=True)),
                ('sub_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.subkeywordmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LongTailKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtail_name', models.TextField(blank=True, null=True)),
                ('shorten_name', models.TextField(blank=True, null=True)),
                ('link_href', models.TextField(blank=True, null=True)),
                ('link_href_shorten_name', models.TextField(blank=True, null=True)),
                ('main_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.mainkeywordmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('page_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.pagelistmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('image_link', models.FileField(blank=True, null=True, upload_to='')),
                ('image_alt', models.TextField(blank=True, null=True)),
                ('tag', models.ManyToManyField(to='keywordapp.TagModel')),
            ],
        ),
    ]
