# Generated by Django 3.2 on 2022-06-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=255)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('page_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.pagelistmodel')),
            ],
        ),
    ]
