# Generated by Django 3.2 on 2022-06-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0002_footerkeywordmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLongTailKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtail_name', models.TextField(blank=True, null=True)),
                ('shorten_name', models.TextField(blank=True, null=True)),
                ('link_href', models.TextField(blank=True, null=True)),
                ('link_href_shorten_name', models.TextField(blank=True, null=True)),
                ('footer_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.footerkeywordmodel')),
            ],
        ),
    ]
