# Generated by Django 3.2 on 2022-06-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0003_footerlongtailkeywordmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFooterKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=255)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.footerkeywordmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubFooterLongTailKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtail_name', models.TextField(blank=True, null=True)),
                ('shorten_name', models.TextField(blank=True, null=True)),
                ('link_href', models.TextField(blank=True, null=True)),
                ('link_href_shorten_name', models.TextField(blank=True, null=True)),
                ('sub_footer_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.subfooterkeywordmodel')),
            ],
        ),
    ]
