# Generated by Django 3.2 on 2022-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0005_auto_20220617_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempKeywordSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_search', models.CharField(blank=True, max_length=255, null=True)),
                ('refine_popular', models.TextField(blank=True, null=True)),
                ('longtail', models.TextField(blank=True, null=True)),
                ('related', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='keyword_search', max_length=255, null=True)),
            ],
        ),
    ]
