# Generated by Django 3.2 on 2022-06-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0006_tempkeywordsearch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempKeywordSearch',
            new_name='TempKeywordSearchModel',
        ),
    ]
