# Generated by Django 3.2 on 2022-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0008_countduplicatedword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='paragraph', max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountDuplicatedWord',
        ),
    ]
