# Generated by Django 3.2 on 2022-07-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0010_auto_20220623_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='countkeywordmodel',
            name='all_amount_in_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FooterModel',
        ),
    ]
