# Generated by Django 3.2 on 2022-07-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0011_auto_20220701_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countkeywordmodel',
            name='all_amount_in_db',
        ),
        migrations.CreateModel(
            name='CountKeywordModelInAllPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('page_list', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='keywordapp.pagelistmodel')),
            ],
        ),
    ]
