# Generated by Django 3.2 on 2022-07-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0014_weblistmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountKeywordModel',
        ),
    ]
