# Generated by Django 3.2 on 2022-09-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0016_tempkeywordsearchmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subfooterkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
