# Generated by Django 3.2 on 2022-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0017_auto_20220917_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subfooterkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subkeywordmodel',
            name='destination_tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
