# Generated by Django 3.2 on 2023-03-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0018_auto_20220917_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempListOfWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
