# Generated by Django 3.2 on 2023-03-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0019_templistofworkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='templistofworkmodel',
            name='content',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='templistofworkmodel',
            name='date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='templistofworkmodel',
            name='header',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='templistofworkmodel',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
