# Generated by Django 3.2 on 2023-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0021_auto_20230329_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempListOfHouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='', max_length=255)),
                ('link', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
