# Generated by Django 3.2 on 2023-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0022_templistofhousemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templistofhousemodel',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='templistofworkmodel',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
