# Generated by Django 3.2 on 2023-04-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0024_auto_20230413_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLinkOfHouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
