# Generated by Django 3.2 on 2023-04-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0028_refreshcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshcheck',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
