# Generated by Django 3.2 on 2023-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0034_alter_refreshcheck_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofhousemodel',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='listofworkmodel',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
