# Generated by Django 3.2 on 2023-04-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0035_auto_20230418_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOfHouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkOfWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
